blank_issues_enabled: false
contact_links:
  - name: Email
    url: mailto:kontakt@nicokempe.de
    about: For really urgent matters, I can respond to emails the fastest.
  - name: Discord
    url: https://discord.gg/t9frQmmqPe
    about: Ask questions and discuss with others in real time on my Discord server!
